# Generated by Django 5.0 on 2024-01-07 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customuser_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.TimeField(default=datetime.datetime(2024, 1, 7, 16, 9, 59, 761334, tzinfo=datetime.timezone.utc)),
        ),
    ]
