# Generated by Django 5.0 on 2024-01-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_currency_item_delivery_price_item_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('USD', 'United States dollar'), ('Euro', 'EURO')], default='PLN', max_length=20),
        ),
    ]
