# Generated by Django 5.0 on 2024-01-07 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.TimeField(default=datetime.datetime(2024, 1, 7, 16, 12, 58, 581022, tzinfo=datetime.timezone.utc)),
        ),
    ]
