# Generated by Django 5.0 on 2024-01-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_total_price_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Decoration', 'Decoration'), ('Food', 'Food'), ('One Piece', 'One Piece'), ('Electronics', 'Electronics')], default='Other', max_length=40),
        ),
    ]
