# Generated by Django 5.0 on 2024-01-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(blank=True, choices=[('Other', 'Other'), ('Decoration', 'Decoration'), ('Food', 'Food'), ('One Piece', 'One Piece'), ('Electronics', 'Electronics')], default='Other', to='store.item'),
        ),
    ]
