# Generated by Django 5.0 on 2024-01-08 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_customuser_date_joined_alter_message_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.TimeField(default=datetime.datetime(2024, 1, 8, 20, 27, 16, 703482, tzinfo=datetime.timezone.utc)),
        ),
    ]
