# Generated by Django 5.0 on 2024-01-09 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='item',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.TimeField(default=datetime.datetime(2024, 1, 9, 18, 55, 56, 517374, tzinfo=datetime.timezone.utc)),
        ),
    ]
