# Generated by Django 5.0 on 2024-01-09 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_item_currency_remove_item_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.TimeField(default=datetime.datetime(2024, 1, 9, 18, 58, 7, 68710, tzinfo=datetime.timezone.utc)),
        ),
    ]
